name: Artifact

on: [push]

env:
  ART_NAME: myartifact


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ART_NAME }}
          path: .
